DrinksMachine.WebUI/Controllers/DrinksController.cs
using DrinksMachine.Services;
using DrinksMachine.WebUI.Models;
using System.Linq;
using System.Web.Mvc;

namespace DrinksMachine.Controllers
{
    public class DrinksController : Controller
    {
        private readonly DrinksServices _drinksServices;
        private VendingMachineViewModel theViewModel;

        public DrinksController()
        {
            _drinksServices = new DrinksServices();
        }

        public ActionResult Index()
        {
            theViewModel = new VendingMachineViewModel()
            {
                allDrinks = _drinksServices.GetDrinks(),
                cashInHand = _drinksServices.GetCash()
            };

            theViewModel.stockInfoCoke = _drinksServices.GetDrinks("Coke");
            theViewModel.stockInfoPepsi = _drinksServices.GetDrinks("Pepsi");
            theViewModel.stockInfoSoda = _drinksServices.GetDrinks("Soda");

            theViewModel.quantityInHandPennies = _drinksServices.GetCash("Penny").QuantityInHand;
            theViewModel.quantityInHandNickels = _drinksServices.GetCash("Nickel").QuantityInHand;
            theViewModel.quantityInHandDimes = _drinksServices.GetCash("Dime").QuantityInHand;
            theViewModel.quantityInHandQuarters = _drinksServices.GetCash("Quarter").QuantityInHand;

            theViewModel.quantityInStockCoke = theViewModel.stockInfoCoke.QuantityInStock;
            theViewModel.quantityInStockPepsi = theViewModel.stockInfoPepsi.QuantityInStock;
            theViewModel.quantityInStockSoda = theViewModel.stockInfoSoda.QuantityInStock;

            theViewModel.rateCoke = theViewModel.stockInfoCoke.ProductPrice;
            theViewModel.ratePepsi = theViewModel.stockInfoPepsi.ProductPrice;
            theViewModel.rateSoda = theViewModel.stockInfoSoda.ProductPrice;

            return View(theViewModel);
        }

        [HttpPost]
        public ActionResult Index(VendingMachineViewModel theModel)
        {
            theModel.stockInfoCoke = _drinksServices.GetDrinks("Coke");
            theModel.stockInfoPepsi = _drinksServices.GetDrinks("Pepsi");
            theModel.stockInfoSoda = _drinksServices.GetDrinks("Soda");

            if (ModelState.IsValid)
            {
                var saleAmtCoke = theModel.quantityRequiredCoke > 0 ? theModel.quantityRequiredCoke * theModel.stockInfoCoke.ProductPrice : 0;
                var saleAmtPepsi = theModel.quantityRequiredPepsi > 0 ? theModel.quantityRequiredPepsi * theModel.stockInfoPepsi.ProductPrice : 0;
                var saleAmtSoda = theModel.quantityRequiredSoda > 0 ? theModel.quantityRequiredSoda * theModel.stockInfoSoda.ProductPrice : 0;
                theModel.saleAmount = (int)(saleAmtCoke + saleAmtPepsi + saleAmtSoda);

                var paidQtyPenny = theModel.quantityPaidPennies > 0 ? theModel.quantityPaidPennies : 0;
                var paidQtyNiclkel = theModel.quantityPaidNickels > 0 ? theModel.quantityPaidNickels * 5 : 0;
                var paidQtyDimes = theModel.quantityPaidDimes > 0 ? theModel.quantityPaidDimes * 10 : 0;
                var paidQtyQuarters = theModel.quantityPaidQuarters > 0 ? theModel.quantityPaidQuarters * 25 : 0;
                theModel.paidAmount = (int)(paidQtyPenny + paidQtyNiclkel + paidQtyDimes + paidQtyQuarters);

                if (theModel.saleAmount.Equals(theModel.paidAmount))
                {
                    theModel.userMessage = $@"Thanks for buying drink \n please collect your drink!";

                    // Add cash received
                    if (theModel.quantityPaidPennies > 0) theModel.quantityInHandPennies += theModel.quantityPaidPennies;
                    if (theModel.quantityPaidNickels > 0) theModel.quantityInHandNickels += theModel.quantityPaidNickels;
                    if (theModel.quantityPaidDimes > 0) theModel.quantityInHandDimes += theModel.quantityPaidDimes;
                    if (theModel.quantityPaidQuarters > 0) theModel.quantityInHandQuarters += theModel.quantityPaidQuarters;

                    // Remove stock sold
                    if (theModel.quantityRequiredCoke > 0) theModel.quantityInStockCoke -= theModel.quantityRequiredCoke;
                    if (theModel.quantityRequiredPepsi > 0) theModel.quantityInStockPepsi -= theModel.quantityRequiredPepsi;
                    if (theModel.quantityRequiredSoda > 0) theModel.quantityInStockSoda -= theModel.quantityRequiredSoda;
                }
                else if (theModel.saleAmount > theModel.paidAmount)
                {
                    var amtDifference = theModel.saleAmount - theModel.paidAmount;
                    theModel.userMessage = $@"You need to pay {amtDifference} to complete this purchase!";
                }
                else //if (theModel.saleAmount < theModel.paidAmount)
                {
                    var amtDifference = theModel.paidAmount - theModel.saleAmount;
                    var totalChange = amtDifference;

                    // Calclulate change to return
                    theModel.quantityReturndedQuarters = amtDifference / 25;
                    amtDifference %= 25;
                    theModel.quantityReturndedDimes = amtDifference / 10;
                    amtDifference %= 10;
                    theModel.quantityReturndedNickels = amtDifference / 5;
                    theModel.quantityReturndedPennies = amtDifference % 5;

                    // Add cash received
                    if (theModel.quantityPaidPennies > 0) theModel.quantityInHandPennies += theModel.quantityPaidPennies;
                    if (theModel.quantityPaidNickels > 0) theModel.quantityInHandNickels += theModel.quantityPaidNickels;
                    if (theModel.quantityPaidDimes > 0) theModel.quantityInHandDimes += theModel.quantityPaidDimes;
                    if (theModel.quantityPaidQuarters > 0) theModel.quantityInHandQuarters += theModel.quantityPaidQuarters;

                    // Remove stock sold
                    if (theModel.quantityRequiredCoke > 0) theModel.quantityInStockCoke -= theModel.quantityRequiredCoke;
                    if (theModel.quantityRequiredPepsi > 0) theModel.quantityInStockPepsi -= theModel.quantityRequiredPepsi;
                    if (theModel.quantityRequiredSoda > 0) theModel.quantityInStockSoda -= theModel.quantityRequiredSoda;

                    // Remove cash returned
                    if (theModel.quantityReturndedPennies > 0) theModel.quantityInHandPennies -= theModel.quantityReturndedPennies;
                    if (theModel.quantityReturndedNickels > 0) theModel.quantityInHandNickels -= theModel.quantityReturndedNickels;
                    if (theModel.quantityReturndedDimes > 0) theModel.quantityInHandDimes -= theModel.quantityReturndedDimes;
                    if (theModel.quantityReturndedQuarters > 0) theModel.quantityInHandQuarters -= theModel.quantityReturndedQuarters;

                    theModel.userMessage = $@"Thanks for buying drink \n please collect your drink and cash {totalChange}! \n {theModel.quantityReturndedPennies} Pennies, {theModel.quantityReturndedNickels} Nickels, {theModel.quantityReturndedDimes} Dimes, {theModel.quantityReturndedQuarters} Quarters!";
                }

            }

            return View(theModel);
        }

    }
}

DrinksMachine.WebUI/Views/Drinks/Index.cshtml
@model DrinksMachine.WebUI.Models.VendingMachineViewModel

@{
    ViewBag.Title = "Drinks Vending Machine";
}
@using (Html.BeginForm("Index", "Drinks", null, FormMethod.Post, new { @id = "drinksForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.quantityInHandPennies)
    @Html.HiddenFor(model => model.quantityInHandNickels)
    @Html.HiddenFor(model => model.quantityInHandDimes)
    @Html.HiddenFor(model => model.quantityInHandQuarters)
    @Html.HiddenFor(model => model.quantityInStockCoke)
    @Html.HiddenFor(model => model.quantityInStockPepsi)
    @Html.HiddenFor(model => model.quantityInStockSoda)
    @Html.HiddenFor(model => model.rateCoke)
    @Html.HiddenFor(model => model.ratePepsi)
    @Html.HiddenFor(model => model.rateSoda)
    <div class="container">
        <div class="card text-white bg-info border-danger">
            <div class="card-header">
                <h4>@ViewBag.Title</h4>
            </div>
            <div class="card-body">
                <h4>COINS INFORMATION</h4>
                <div class="form-horizontal col-md-12">
                    <div class="form-group">
                        <div class="row col-md-12">
                            <div class="col-md-3">
                                <label class="control-label h3" for="quantityPaidPennies">Pennies </label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label h3" for="quantityPaidNickels">Nickels </label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label h3" for="quantityPaidDimes">Dimes </label>
                            </div>
                            <div class="col-md-3">
                                <label class="control-label h3" for="quantityPaidQuarters">Quarters </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row col-md-12">
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.quantityPaidPennies, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.quantityPaidNickels, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.quantityPaidDimes, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                            <div class="col-md-3">
                                @Html.EditorFor(model => model.quantityPaidQuarters, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                    </div>

                    <br />
                    <br />
                    <h4>PRODUCTS INFORMATION</h4>
                    <br />
                    <br />
                    <div class="form-group">
                        <div class="row col-md-12">
                            <div class="col-md-3">
                                <label class="control-label h3" for="quantityRequiredCoke">
                                    Coke
                                </label> <br />
                                @Model.quantityInStockCoke drinks available, Cost = @Model.stockInfoCoke.ProductPrice
                            </div>
                            <div class="col-md-3">
                                @{
                                    if (Model.quantityInStockCoke > 0)
                                    {
                                        @Html.EditorFor(model => model.quantityRequiredCoke, new { htmlAttributes = new { @class = "form-control" } })
                                    }
                                    else
                                    {
                                        <div class="form-control">out of stock</div>
                                    }
                                }
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row col-md-12">
                            <div class="col-md-3">
                                <label class="control-label h3" for="quantityRequiredPepsi">
                                    Pepsi
                                </label> <br />
                                @Model.quantityInStockPepsi drinks available, Cost = @Model.stockInfoPepsi.ProductPrice
                            </div>
                            <div class="col-md-3">
                                @{
                                    if (Model.quantityInStockCoke > 0)
                                    {
                                        @Html.EditorFor(model => model.quantityRequiredPepsi, new { htmlAttributes = new { @class = "form-control" } })
                                    }
                                    else
                                    {
                                        <div class="form-control">out of stock</div>
                                    }
                                }
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row col-md-12">
                            <div class="col-md-3">
                                <label class="control-label h3" for="quantityRequiredSoda">
                                    Soda
                                </label> <br />
                                @Model.quantityInStockSoda drinks available, Cost = @Model.stockInfoSoda.ProductPrice
                            </div>
                            <div class="col-md-3">
                                @{
                                    if (Model.quantityInStockCoke > 0)
                                    {
                                        @Html.EditorFor(model => model.quantityRequiredSoda, new { htmlAttributes = new { @class = "form-control" } })
                                    }
                                    else
                                    {
                                        <div class="form-control">out of stock</div>
                                    }
                                }
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row col-md-12">
                            <div class="col-md-6">
                                <label class="control-label h3" for="saleAmount">Order Total </label>
                            </div>
                            <div class="col-md-6">
                                <label class="control-label h3" for="paidAmount">Total Paid </label>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="row col-md-12">
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.saleAmount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            </div>
                            <div class="col-md-6">
                                @Html.EditorFor(model => model.paidAmount, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="card-footer align-self-center">
                <input class="btn btn-success btn-lg btn-block" type="submit" Name="getDrinks" VALUE="Get Drinks" id="getDrinks">
            </div>
        </div>
    </div>
}
@section scripts
{

    <script type="text/javascript">

        $(document).ready(function() {
            var msg = '@Model.userMessage';
            if (msg) {

                swal({
                    title: "Done",
                    text: msg,
                    type: "success",
                    //showCancelButton: true,
                    confirmButtonColor: '#DD6B55',
                    confirmButtonText: 'OK',
                    //cancelButtonText: "No, cancel it!",
                    closeOnConfirm: true,
                    closeOnCancel: true
                },
                function (isConfirm) {
                    if (isConfirm) {
                        console.log('confirm');
                    } else {
                        console.log('not confirm');
                    }
                });


            }
        });

        $("body").on("blur", "#quantityRequiredCoke", function (e) {
            setSaleAmount();
        });

        $("body").on("blur", "#quantityRequiredPepsi", function (e) {
            setSaleAmount();
        });

        $("body").on("blur", "#quantityRequiredSoda", function (e) {
            setSaleAmount();
        });

        function setSaleAmount() {
            var requiredCoke = Number($("#quantityRequiredCoke").val());
            var requiredPepsi = Number($("#quantityRequiredPepsi").val());
            var requiredSoda = Number($("#quantityRequiredSoda").val());
            if (requiredCoke == 0 && requiredPepsi == 0 && requiredSoda == 0)
                return;

            var rateCoke = parseInt(@Model.rateCoke);
            var ratePepsi = parseInt(@Model.ratePepsi);
            var rateSoda = parseInt(@Model.rateSoda);

            var amountCoke = requiredCoke * rateCoke;
            var amountPepsi = requiredPepsi * ratePepsi;
            var amountSoda = requiredSoda * rateSoda;

            var totalAmount = amountCoke + amountPepsi + amountSoda;

            $("#saleAmount").val(totalAmount);
        }


        $("body").on("blur", "#quantityPaidPennies", function (e) {
            setPaidAmount();
        });

        $("body").on("blur", "#quantityPaidNickels", function (e) {
            setPaidAmount();
        });

        $("body").on("blur", "#quantityPaidDimes", function (e) {
            setPaidAmount();
        });

        $("body").on("blur", "#quantityPaidQuarters", function (e) {
            setPaidAmount();
        });

        function setPaidAmount() {
            var paidPennies = Number($("#quantityPaidPennies").val());
            var paidNickels = Number($("#quantityPaidNickels").val());
            var paidDimes = Number($("#quantityPaidDimes").val());
            var paidQuarters = Number($("#quantityPaidQuarters").val());
            if (paidPennies == 0 && paidNickels == 0 && paidDimes == 0 && paidQuarters == 0)
                return;

            var totalPaidAmount = paidPennies;
            if (paidNickels > 0) totalPaidAmount += (paidNickels * 5)
            if (paidDimes > 0) totalPaidAmount += (paidDimes * 10)
            if (paidQuarters > 0) totalPaidAmount += (paidQuarters * 25)

            $("#paidAmount").val(totalPaidAmount);

            var totalSaleAmount = Number($("#saleAmount").val());
            if (totalPaidAmount > 0 && totalSaleAmount > 0 && (totalPaidAmount >= totalSaleAmount)) {
                $('#getDrinks').removeAttr('disabled');
            }
            else {
                $('#getDrinks').attr('disabled', 'disabled');
            }
        }
    </script>

}